### ISSUE TITLE
net::err_file_no_found (file:///index.html)

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/cordova-wrapper#6]
Problem:
User attempts to log into erpnext via app, receives this error:

```
net::err_file_no_found (file:///index.html)
```

Issue thread:
https://discuss.erpnext.com/t/android-was-working-now-an-error/17099

Possible solution:

http://stackoverflow.com/questions/27496411/cordova-err-file-not-foundfile-android-assets-www-index-html

**Comment by GSLabIt** [comment]
getting same problem, any news on this?

**Comment by fahimalizain** [comment]
Issue comes when having a custom app with any of `app_includes_js` and `app_include_css`.
I am using jasper_erpnext_report, and when I remove those lines from the hooks file, the mobile app runs fine.

**Comment by GSLabIt** [comment]
Ah, that's awful :( .. @netchampfaris any hint on how to fix it?

**Comment by fahimalizain** [comment]
@umairsy @netchampfaris  looks like the code is not updated in this repo ?

**Comment by netchampfaris** [comment]
@faztp12 Thanks for the tip. I didn't realize that was the problem.

**Comment by fahimalizain** [comment]
@netchampfaris I think your fork `netchampfaris/mobile-1` `new-master` is the latest version.

**Comment by netchampfaris** [comment]
@faztp12 You are right, just updated to latest 0.0.8
